### PR TITLE
Character

### PR DESCRIPTION
**Pull request by L3nn0x**
Do not delete the branch after merging as I want to continue working on it to polish the implementation

---
This change is [Reviewable](https://reviewable.io/reviews/ravenx8/osirose-new/65)

### CODE REVIEW

**Comment by L3nn0x** [comment]
#53 is implemented 
#42 is partially implemented
#40 the normal chatting system is implemented
#39 is implemented
#14 is partially implemented (lacking quests and saving to database)

**Comment by RavenX8** [comment]
Reviewed 28 of 29 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/map/include/entitySystems.h, line 46 at r2](https://reviewable.io:443/reviews/ravenx8/osirose-new/65#-KSyhFpkAmI_NfCZeUVq:-KSyhFpkAmI_NfCZeUVr:b-9krpro) ([raw file](https://github.com/ravenx8/osirose-new/blob/d31f0b6873f975ae520d492227f8109eb50c3c0b/src/map/include/entitySystems.h#L46)):*
> ```objc
>                 position->x_ += dx * speed * dt;
>                 position->y_ += dy * speed * dt;
>                 if (position->x_ == destination->x_ && position->y_ == destination->y_)
> ```

This still needs to be fixed at some point in the future.

---

*[src/map/src/entitysystem.cpp, line 6 at r2](https://reviewable.io:443/reviews/ravenx8/osirose-new/65#-KSyiN3c2RjO_Xt1GGhd:-KSyiN3dsEQeOlf9udQm:b-auvxnp) ([raw file](https://github.com/ravenx8/osirose-new/blob/d31f0b6873f975ae520d492227f8109eb50c3c0b/src/map/src/entitysystem.cpp#L6)):*
> ```cpp
> Entity EntitySystem::loadCharacter(uint32_t charId, bool platinium) {
>     auto &database = Core::databasePool.getDatabase();
>     auto res = database.QStore(fmt::format("CALL GetCharacter({});", charId));
> ```

This needs to be fixed. GetCharacter does not exist anymore. Should be get_character

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ravenx8/osirose-new/65)*

**Comment by RavenX8** [comment]
Reviewed 13 of 14 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/src/cnetwork_asio.cpp, line 223 at r4](https://reviewable.io:443/reviews/ravenx8/osirose-new/65#-KTUw3epxqfFGQB5M5LA:-KTUw3epxqfFGQB5M5LB:b-4j7gu) ([raw file](https://github.com/ravenx8/osirose-new/blob/30f1e3858b24d164a41b50f3d749f025cfc99f95/src/core/src/cnetwork_asio.cpp#L223)):*
> ```cpp
>             }
>           } else {
>             if (errorCode.value() == 2 || errorCode.value() == 104) {
> ```

We should find the actual enum names for these error codes. asio::error::basic_error::*

---

*[src/rosecommon/include/entityComponents.h, line 277 at r4](https://reviewable.io:443/reviews/ravenx8/osirose-new/65#-KTUvNaQDPf2RCU2LNc1:-KTUvNaQDPf2RCU2LNc2:by5mays) ([raw file](https://github.com/ravenx8/osirose-new/blob/30f1e3858b24d164a41b50f3d749f025cfc99f95/src/rosecommon/include/entityComponents.h#L277)):*
> ```objc
>     enum ItemType {
>         WEARABLE = 0,
>         CONSOMABLE = 1,
> ```

correct spelling would be CONSUMABLE.

---

*[src/rosecommon/include/mappackets.h, line 280 at r4](https://reviewable.io:443/reviews/ravenx8/osirose-new/65#-KTUvqkn-QuGrPqW3qYP:-KTUvqkn-QuGrPqW3qYQ:b792vmp) ([raw file](https://github.com/ravenx8/osirose-new/blob/30f1e3858b24d164a41b50f3d749f025cfc99f95/src/rosecommon/include/mappackets.h#L280)):*
> ```objc
>         *this << basic->name_; //szUserID
> 
>         *this << basic->name_; //Avatar name
> ```

Why is there statement here twice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ravenx8/osirose-new/65)*

**Comment by RavenX8** [comment]
Reviewed 7 of 13 files at r5, 2 of 3 files at r6, 20 of 20 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/rosecommon/include/entityComponents.h, line 367 at r7](https://reviewable.io:443/reviews/ravenx8/osirose-new/65#-KTtzfuhe3_qMxCR_Llc:-KTtzfuhe3_qMxCR_Lld:b-3xb1vg) ([raw file](https://github.com/ravenx8/osirose-new/blob/b531303b89115025b5d42cb493abee3f4333ec7d/src/rosecommon/include/entityComponents.h#L367)):*
> ```objc
>         ENGINE = 1,
>         LEGS,
>         //OPTION, // weapon or back seat
> ```

We still need to know why this is having an issue. The client expects this to be there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ravenx8/osirose-new/65)*

**Pull request merged**
